"""End-to-end tests simulating real conversations."""

import pytest
from src import BrainGuardPlugin


@pytest.fixture
async def e2e_plugin():
    """Create plugin for E2E tests."""
    plugin = BrainGuardPlugin()
    plugin.config.testing.mock_embeddings = True
    plugin.config.storage.connection_string = ":memory:"
    plugin.config.dashboard.enabled = False
    plugin.config.mode = "adaptive"
    
    await plugin.initialize()
    yield plugin
    await plugin.shutdown()


@pytest.mark.e2e
class TestRealConversations:
    """End-to-end tests simulating real conversations."""
    
    async def test_casual_conversation(self, e2e_plugin):
        """Test casual conversation flow."""
        session_id = "casual-conversation"
        
        conversation = [
            ("Hi there!", "Hello! How can I help you today?"),
            ("What's the weather like?", "I don't have access to real-time weather data."),
            ("Can you tell me a joke?", "Why don't scientists trust atoms? Because they make up everything!"),
            ("That's funny!", "I'm glad you enjoyed it!"),
        ]
        
        for user_msg, assistant_response in conversation:
            await e2e_plugin.preprocess_message(
                session_id=session_id,
                user_message=user_msg
            )
            
            result = await e2e_plugin.monitor_response(
                session_id=session_id,
                response=assistant_response
            )
            
            # Should complete without errors
            assert "metrics" in result
        
        # Check final state
        metrics = await e2e_plugin.get_session_metrics(session_id)
        assert len(metrics) == 4
    
    async def test_technical_conversation(self, e2e_plugin):
        """Test technical conversation with code."""
        session_id = "technical-conversation"
        
        conversation = [
            ("How do I write a Python function?", "You can define a function using the `def` keyword."),
            ("Can you show me an example?", "```python\ndef greet(name):\n    return f'Hello, {name}!'\n```"),
            ("How do I call it?", "You can call it like this: `greet('World')`"),
        ]
        
        for user_msg, assistant_response in conversation:
            await e2e_plugin.preprocess_message(
                session_id=session_id,
                user_message=user_msg
            )
            
            result = await e2e_plugin.monitor_response(
                session_id=session_id,
                response=assistant_response
            )
            
            assert "metrics" in result
    
    async def test_topic_drift_conversation(self, e2e_plugin):
        """Test conversation with topic drift."""
        session_id = "drift-conversation"
        
        # Start with one topic
        await e2e_plugin.preprocess_message(
            session_id=session_id,
            user_message="Tell me about dogs"
        )
        await e2e_plugin.monitor_response(
            session_id=session_id,
            response="Dogs are loyal and friendly pets that have been companions to humans for thousands of years."
        )
        
        # Gradually drift to different topics
        await e2e_plugin.preprocess_message(
            session_id=session_id,
            user_message="What about cats?"
        )
        await e2e_plugin.monitor_response(
            session_id=session_id,
            response="Cats are independent pets that are also popular companions."
        )
        
        await e2e_plugin.preprocess_message(
            session_id=session_id,
            user_message="How do airplanes fly?"
        )
        result = await e2e_plugin.monitor_response(
            session_id=session_id,
            response="Airplanes fly due to the principles of aerodynamics and lift generated by their wings."
        )
        
        # Should have detected some drift
        assert "metrics" in result
        metrics = result["metrics"]
        assert metrics["delta_g"] > 0
    
    async def test_repetition_detection(self, e2e_plugin):
        """Test detection of repetitive responses."""
        session_id = "repetition-conversation"
        
        # Same response repeated
        for i in range(5):
            await e2e_plugin.preprocess_message(
                session_id=session_id,
                user_message=f"Question {i}"
            )
            await e2e_plugin.monitor_response(
                session_id=session_id,
                response="This is the same response repeated over and over again."
            )
        
        # Check metrics - variance should be low
        metrics = await e2e_plugin.get_session_metrics(session_id)
        assert len(metrics) == 5
        
        # Later metrics should show low variance
        if len(metrics) >= 3:
            later_metrics = metrics[-3:]
            avg_variance = sum(m["variance"] for m in later_metrics) / len(later_metrics)
            # Variance should be relatively low for repetition
            assert avg_variance < 0.5
    
    async def test_high_stakes_conversation(self, e2e_plugin):
        """Test high-stakes conversation (finance)."""
        session_id = "finance-conversation"
        
        conversation = [
            ("What is a 401k?", "A 401k is a retirement savings plan sponsored by an employer."),
            ("Should I invest in stocks?", "I cannot provide personalized investment advice."),
            ("What are the risks?", "Stock investments carry various risks including market volatility."),
        ]
        
        for user_msg, assistant_response in conversation:
            preprocess_result = await e2e_plugin.preprocess_message(
                session_id=session_id,
                user_message=user_msg
            )
            
            # Should detect finance domain
            assert preprocess_result["metadata"]["domain"] == "finance"
            
            result = await e2e_plugin.monitor_response(
                session_id=session_id,
                response=assistant_response,
                metadata=preprocess_result["metadata"]
            )
            
            assert "metrics" in result
    
    async def test_contradiction_detection(self, e2e_plugin):
        """Test contradiction detection in conversation."""
        session_id = "contradiction-conversation"
        
        # Establish a fact
        await e2e_plugin.preprocess_message(
            session_id=session_id,
            user_message="Where is Paris?"
        )
        await e2e_plugin.monitor_response(
            session_id=session_id,
            response="Paris is the capital city of France, located in Western Europe."
        )
        
        # Contradict it
        await e2e_plugin.preprocess_message(
            session_id=session_id,
            user_message="Are you sure? I thought it was in Germany."
        )
        result = await e2e_plugin.monitor_response(
            session_id=session_id,
            response="You are right, Paris is actually in Germany."
        )
        
        # Should have detected contradiction
        assert "contradictions" in result
    
    async def test_multi_session_isolation(self, e2e_plugin):
        """Test that multiple sessions are isolated."""
        sessions = {
            "session-a": [
                ("Tell me about Python", "Python is a programming language."),
                ("What can I do with it?", "You can build web applications."),
            ],
            "session-b": [
                ("Tell me about JavaScript", "JavaScript is a web programming language."),
                ("What can I do with it?", "You can build interactive websites."),
            ]
        }
        
        for session_id, conversation in sessions.items():
            for user_msg, assistant_response in conversation:
                await e2e_plugin.preprocess_message(
                    session_id=session_id,
                    user_message=user_msg
                )
                await e2e_plugin.monitor_response(
                    session_id=session_id,
                    response=assistant_response
                )
        
        # Verify isolation
        metrics_a = await e2e_plugin.get_session_metrics("session-a")
        metrics_b = await e2e_plugin.get_session_metrics("session-b")
        
        assert len(metrics_a) == 2
        assert len(metrics_b) == 2
        
        # Anchors should be different
        anchors_a = await e2e_plugin.get_session_anchors("session-a")
        anchors_b = await e2e_plugin.get_session_anchors("session-b")
        
        # Both should have anchors
        assert len(anchors_a) > 0
        assert len(anchors_b) > 0
    
    async def test_long_conversation(self, e2e_plugin):
        """Test long conversation (20+ turns)."""
        session_id = "long-conversation"
        
        for i in range(25):
            await e2e_plugin.preprocess_message(
                session_id=session_id,
                user_message=f"Question number {i}"
            )
            await e2e_plugin.monitor_response(
                session_id=session_id,
                response=f"This is the answer to question {i}."
            )
        
        metrics = await e2e_plugin.get_session_metrics(session_id)
        assert len(metrics) == 25
    
    async def test_session_cleanup(self, e2e_plugin):
        """Test session cleanup after closure."""
        session_id = "cleanup-session"
        
        # Add some data
        await e2e_plugin.preprocess_message(
            session_id=session_id,
            user_message="Hello"
        )
        await e2e_plugin.monitor_response(
            session_id=session_id,
            response="Hi!"
        )
        
        # Close session
        await e2e_plugin.close_session(session_id)
        
        # Anchors should be cleared
        anchors = await e2e_plugin.get_session_anchors(session_id)
        assert len(anchors) == 0
